blog/urls.py
from django.urls import path, include
from .views.article_v import *
from .views.subncategories_v import *
from .views.dashboard.dashboard_home_v import *
from .views.dashboard.dashboard_article_v import *
from .views.dashboard.dashboard_many_v import *
from .views.dashboard.subncategory_d_v import *
from .views.tags_v import tag_blogs
from .views.dynamic_search_JS_V import *


app_name = 'blog'

urlpatterns = [
    path('articles-available/', blog_home, name='blog_home'),
    path('article view/<slug:slug>/', blog_detail, name='blog_detail'),
    path('category article list/<slug:slug>/', category_detail, name='category_detail'),
    path('subcategory article list/<slug:slug>/', subcategory_detail, name='subcategory_detail'),
    path('artcles/tagged/<slug:tag_slug>/', tag_blogs, name='tag_blogs'),
    
    #Dashboard Views
    # path('<slug:slug>/', article_detail, name='article_detail')
    path('dashboard/', dashboard_home, name='dashboard_home'),
    path('create/', blog_create, name='blog_create'),
    
    #DASHBOARD >>>>>>> : dashboard_article_v.py
    path('articles/<slug:slug>/', das_article_detail, name='das_article_detail'),
    path('edit/<slug:slug>/', blog_edit, name='blog_edit'),
    path('approve/<slug:slug>/', blog_approve, name='blog_approve'),
    path('reject/<slug:slug>/', blog_reject, name='blog_reject'),
    path('hide/<slug:slug>/', blog_hide, name='blog_hide'),
    path('unhide/<slug:slug>/', blog_unhide, name='blog_unhide'),
    path('delete/<slug:slug>/', blog_delete, name='blog_delete'),
    # used when using the id to get the data
    path('get_category_by_subcategory/<int:subcategory_id>/', 
         get_category_by_subcategory, name='get_category_by_subcategory'),
    # -----------------------------------------------------------//
        #   used when using slug to get the data
    # path('get_category_by_subcategory/<slug:subcategory_slug>/', 
    #      get_category_by_subcategory, name='get_category_by_subcategory'),
       #-----------------------------------------------------------------------//
    #-----------END DASHBOARD >>>>>>> : dashboard_article_v.py ------------//
    
    path('category/create/', category_create, name='category_create'),
    path('category/edit/<int:id>/', category_edit, name='category_edit'), #will be usin the id instead of slug
    path('category-list/', category_list, name='category_list'),
    
    path('subcategory/create/', subcategory_create, name='subcategory_create'),
    path('subcategory/edit/<int:id>/', subcategory_edit, name='subcategory_edit'),
    path('subcategory list/', subcategory_list, name='subcategory_list'),
    # dashboard_many_v.py
    path('recent articles/', recent_article_list, name='recent_article_list'),
    path('drafted articles/', drafted_article_list, name='drafted_article_list'),
    path('published articles/', published_article_list, name='published_article_list'),
    path('deleted articles/', hidden_article_list, name='hidden_article_list'),
    path('written articles/', written_article_list, name='written_article_list'),
    path('approved articles/', approved_article_list, name='approved_article_list'),
    path('rejected articles/', rejected_article_list, name='rejected_article_list'),
    
    # Add this URL pattern for search suggestions
    path('open-dropeddown-article/<slug:articleSlug>/', open_dropdown_article, name='open_dropdown_article'),
    path('blog-search-results/', blog_search_results, name='blog_search_results'),
    path('blog_search/ajax_search/', blog_ajax_search, name='blog_ajax_search'),
    
]

car_garage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# Admin Customization
admin.site.site_header = "Login to CDT"
admin.site.site_title = "Welcome to CDT Dashboard"
admin.site.index_title = "Welcome to this Portal"

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('contact_us/', include('contact_us.urls')),
    path('', include('visitors_counter.urls')),
]
# if settings.DEBUG:# Only add this when we in debug mode
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# else:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/blogdashboard/article_detail.html
{% extends 'blogdashboard/dashboard_base.html' %}
{% comment %} displays blog detail and category lists {% endcomment %}
{% comment %}
    found in blog_detail in article_v.py
{% endcomment %}

{% load static %}


{% block head %}
<title> Blog Detail </title>
<link rel="stylesheet" href="{% static 'css/blog/blog_detail.css' %}">
<link rel="stylesheet" href="{% static 'css/blog/blog_list.css' %}">
<link rel="stylesheet" href="{% static 'css/blog/blog.css' %}">
<link rel="stylesheet" href="{% static 'css/blogdashboard/common.css' %}">
<style>

  .post-list{
    display: block;
  }
  .p-d-body {
    margin-bottom: 5px;
  }
  .time{
    display:flex;
    justify-content: flex-end;
    margin-bottom: 40px ;
  }
  .time .btn{
    margin-right: 20px;
    border: 1px solid;
    background-color: white;
  }
  .rejected{
    color: red;
    font-weight: 600;
  }
  .post-header li .confirm-btn{
    background-color: white;
    border: 2px red solid;
    border-radius: 9px;
    padding: 0 10px;
  }
</style>
{% endblock head %}

{% block content %}
<section class="p-detail post-list">

    <div class="p-l-main p-d-main item2 container-xxl">
        <!-- Geting Category that is holding the Subcategory -->
        <div>
        <h5 class="p-d-header p-d-info">
            <a href="{{category.get_absolute_url }}" style="text-decoration: none;">
                {{ blog.category }}
            </a> 
            <a href="{{subcategory.get_absolute_url }}" style="text-decoration: none;">
                <span id="span-h">></span> 
                {{ blog.subcategory }}
            </a>
            <span id="span-h">></span>
            {{ blog.title }}


        </h5>
        </div>
        <div class="p-d-body">
            <div class="p-d-container">
                <div class="p-d-banner">
                    <img src="{{blog.image.url}}" alt="{{ blog.title }}">
                </div>
                <div class="p-d-profile">
                    <img src="{{ blog.author.profile.image.url}}" alt="Profile image">
                </div>
            </div>
            <div class="p-d-info item2"> 
            <ol class="post-header">
                <li>Arthur<i>:</i> <span>{{ blog.author.username }}</span> </li>
                <li>Created on<i>:</i> <span>{{ blog.date_created|date:"F j, Y" }}</span> </li>
                <li>Status<i>:</i>  {{ blog.status }}</li>
                <li><i class="fa fa-comments"></i> {{ blog.comments.count  }}</li>
                <li><i class="fa fa-eye"></i> {{ blog.formatted_views_count }}</li>
                {% comment %} if rected is True {% endcomment %}
                {% if blog.rejected %} 
                    <li class="rejected">REJECTED <i class="bi bi-x-octagon"></i></li>
                    {% comment %} if approved is True {% endcomment %}
                    <li>
                      <a class="confirm-btn " 
                         data-title="Reasion for Rejecting {{blog.title}}?"
                         data-id = "msg"
                         data-msg="{{ blog.rejection_reason }}" 
                         data-url="{% url 'blog:blog_edit' slug=blog.slug %}" 
                         data-button="Edit the article"
                         data-bs-toggle="modal">
                         Reason for rejecting
                      </a>
                  </li>
                {% elif blog.approved %}
                    <li class="text-success">APPROVED <i class="bi bi-check2-square"></i></li>
                    {% comment %} if none of the above is true {% endcomment %}
                {% else %}
                    <li class="text-info">NOT VERIFIED</li>
                    {% comment %} end {% endcomment %}
                {% endif %}
                
            </ol>
            </div>

            <div class="card-text content">
                {{ blog.content|safe }}
            </div>
            {% comment %} tags {% endcomment %}
            <div class="tags--"> 
              {% comment %} <h6>Tags <i class="bi bi-tags-fill"></i>:</h6> {% endcomment %}
              {% for tag in blog.tags.all %}
              <div class="tag"><i class="bi bi-tags-fill"></i> <a href="{% url 'blog:tag_blogs' tag.slug %}">{{ tag.name }}</a></div>
              {% endfor %}
          </div>
            {% comment %} end of tags {% endcomment %}
        </div>{% comment %}End Of Blog Detail{% endcomment %}
        
       {% comment %} dropdown this Part of the code depends on Modal.js to function {% endcomment %}
       <div class="dropdown time">
        <button class="btn dropdown-toggle" type="button" id="time-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
          {% comment %} <i class="fas fa-chevron-down dropdown-btn"></i> {% endcomment %}
          Article Options<i class="bi bi-box-arrow-up"></i>
        </button>
        <ul class="dropdown-menu" aria-labelledby="time-dropdown">
            <li>
                <a class="dropdown-item confirm-btn" 
                   data-title="Are you sure you want to edit {{blog.title}}?"
                   data-id = "edit"
                   {% comment %} data-message="Once you edit it, original content will be lost."  {% endcomment %}
                   data-url="{% url 'blog:blog_edit' slug=blog.slug %}" 
                   data-button="Edit"
                   data-bs-toggle="modal">
                   Edit Article
                </a>
            </li>
            {% if not blog.hidden %}
          <li><hr class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item confirm-btn" 
               data-title="Are you sure you want to Hide {{blog.title}}?"
               data-id="hide"
               {% comment %} data-message="Once you hide it will not be available for other."  {% endcomment %}
               data-url="{% url 'blog:blog_hide' slug=blog.slug %}" 
               data-button="Hide"
               data-bs-toggle="modal">
               Hide Article
            </a>
          </li>
          {% endif%}
          <li><hr class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item confirm-btn" 
               data-title="Are you sure you want to delete {{blog.title}}?"
               data-message="Once you delete this article, it cannot be recovered." 
               data-url="{% url 'blog:blog_delete' slug=blog.slug %}" 
               data-button="Delete"
               data-bs-toggle="modal">
               Delete
            </a>
          </li>  
          
          {% if request.user.is_superuser or request.user.is_staff %}
          {% comment %} If BLOG IS APPROVED DISPLAY REJECT {% endcomment %}
          {% if blog.approved %}
          <li><hr class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item confirm-btn" 
               data-title="Are you sure you want to Reject {{blog.title}}?"
               data-message="You are about to reject {{blog.title}}. The Author will be notified ." 
               data-url="{% url 'blog:blog_reject' slug=blog.slug %}" 
               data-button="Reject"
               data-bs-toggle="modal">
               Reject
            </a>
          </li>  
          {% comment %} END IF {% endcomment %}
          {% comment %} else if rejected is True {% endcomment %}
          {% elif blog.rejected %}      
          <li><hr class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item confirm-btn" 
               data-title="Are you sure you want to Approve {{blog.title}}?"
               data-message="You are about to approve {{blog.title}}. The Author will be notified ." 
               data-url="{% url 'blog:blog_approve' slug=blog.slug %}" 
               data-button="Approve"
               data-bs-toggle="modal">
               Approve
            </a>
          </li>   
          {% comment %} end {% endcomment %}
          {% comment %} if Blog is not rejected or approved display both buttons {% endcomment %}
          {% else  %}      
          <li><hr class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item confirm-btn" 
               data-title="Are you sure you want to Approve {{blog.title}}?"
               data-message="You are about to approve {{blog.title}}. The Author will be notified ." 
               data-url="{% url 'blog:blog_approve' slug=blog.slug %}" 
               data-button="Approve"
               data-bs-toggle="modal">
               Approve
            </a>
          </li>
          <li><hr class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item confirm-btn" 
               data-title="Are you sure you want to Reject {{blog.title}}?"
               data-message="You are about to reject {{blog.title}}. The Author will be notified ." 
               data-url="{% url 'blog:blog_reject' slug=blog.slug %}" 
               data-button="Reject"
               data-bs-toggle="modal">
               Reject
            </a>
          </li> 
          {% comment %} end of Else {% endcomment %}
          {% endif %} 
          {% endif %}
          <li><hr class="dropdown-divider"></li>
        </ul>
        
    </div>
      {% comment %}end of dropdown {% endcomment %}
    </div> 
    
    
    </div>{% comment %}End Of Main Body{% endcomment %}

</section>
{% endblock content %}

{%block js%}
{%endblock js%}

templates/blogdashboard/dashboard_home.html
{% extends 'blogdashboard/dashboard_base.html' %}

{% comment %} displays blog lists and category lists {% endcomment %}

{% load static %}

{% block head %}
<title> Dashboard Home</title>
<link rel="stylesheet" href="{% static 'css/blogdashboard/dashboard_home.css' %}">
<link rel="stylesheet" href="{% static 'css/blogdashboard/common.css' %}">
<style>
 
</style>
{% endblock head %}

{% block content %}
{% comment %} <!-- home --> {% endcomment %}
<section class="item2 section home-page" id="home">
    {% comment %} dashboard_article_v.py {% endcomment %}
    {% comment %} infor cards  {% endcomment %}
        <div class="info-cards">
            {% comment %} TOTAL NO FO BLOGS WRITTEN{% endcomment %}
            <a href="{% url 'blog:written_article_list' %}">
            <div class="card--item">
                <div id="card--item" style="margin: 0.8rem;">
                    <div class="card-top">
                        <div class="card-title-inf">
                            <span class="card--title ">Articles Written</span>
                            <span id="span2">{{ total_blogs }}</span>
                        </div>
                        <i class="green d-c-fa fa fa-layer-group"></i>
                    </div>
                    <p class="card--footer">Total written articles</p>
                </div>
                <div class="card-bar bg--green"></div>
            </div>
            </a>
            {% comment %} END {% endcomment %}       
            {% comment %} TOTAL NO OF PUBLISHED Articles {% endcomment %}
            <a href="{% url 'blog:published_article_list' %}">
            <div class="card--item">
                <div id="card--item" style="margin: 0.8rem;">
                    <div class="card-top">
                        <div class="card-title-inf">
                            <span class="card--title ">Published Articles</span>
                            <span id="span2">{{ total_published_blogs }}</span>
                        </div>
                        <i class="pink d-c-fa fa fa-layer-group"></i>
                    </div>
                    <p class="card--footer">Total published articles</p>
                </div>
                <div class="card-bar bg--pink"></div>
            </div>
            </a>
            {% comment %} end {% endcomment %}
            {% comment %} total no of Views {% endcomment %}
            <a href="">
            <div class="card--item">
                <div id="card--item" style="margin: 0.8rem;">
                    <div class="card-top">
                        <div class="card-title-inf">
                            <span class="card--title ">Views</span>
                            <span id="span2">{{ total_views }}</span>
                        </div>
                        <i class="blue d-c-fa fa fa-layer-group"></i>
                    </div>
                    <p class="card--footer">Total Views for all Articles</p>
                </div>
                <div class="card-bar bg--blue"></div>
            </div>
            </a>
            {% comment %} end {% endcomment %}
            {% comment %} TOTAL NO OF COMMENTS {% endcomment %}
            <a href="">
            <div class="card--item">
                <div id="card--item" style="margin: 0.8rem;">
                    <div class="card-top">
                        <div class="card-title-inf">
                            <span class="card--title ">Comments</span>
                            <span id="span2">{{ total_comments }}</span>
                        </div>
                        <i class="yellow d-c-fa fa fa-layer-group"></i>
                    </div>
                    <p class="card--footer">Total comments for all articles</p>
                </div>
                <div class="card-bar bg--yellow"></div>
            </div>
            </a>
            {% comment %} END OF COMMENTS {% endcomment %}
            {% comment %} TOTAL NO FO BLOGS Approved{% endcomment %}
            <a href="{% url 'blog:approved_article_list' %}">
            <div class="card--item">
                <div id="card--item" style="margin: 0.8rem;">
                    <div class="card-top">
                        <div class="card-title-inf">
                            <span class="card--title ">Articles Approved</span>
                            <span id="span2">{{ total_approved }}</span>
                        </div>
                        <i class="green d-c-fa fa fa-layer-group"></i>
                    </div>
                    <p class="card--footer">Total approved articles</p>
                </div>
                <div class="card-bar bg--green"></div>
            </div>
            </a>
            {% comment %} END {% endcomment %}
            {% comment %} TOTAL NO FO BLOGS Rejected{% endcomment %}
            <a href="{% url 'blog:rejected_article_list' %}">
            <div class="card--item">
                <div id="card--item" style="margin: 0.8rem;">
                    <div class="card-top">
                        <div class="card-title-inf">
                            <span class="card--title ">Articles Rejected</span>
                            <span id="span2">{{ total_rejected }}</span>
                        </div>
                        <i class="green d-c-fa fa fa-layer-group"></i>
                    </div>
                    <p class="card--footer">Total rejected articles</p>
                </div>
                <div class="card-bar bg--green"></div>
            </div>
            </a>
            {% comment %} END {% endcomment %}
            {% comment %} TOTAL NO FO BLOGS Rejected{% endcomment %}
            <a href="{% url 'blog:hidden_article_list' %}">
            <div class="card--item">
                <div id="card--item" style="margin: 0.8rem;">
                    <div class="card-top">
                        <div class="card-title-inf">
                            <span class="card--title ">Articles Hidden</span>
                            <span id="span2">{{ total_hidden }}</span>
                        </div>
                        <i class="green d-c-fa fa fa-layer-group"></i>
                    </div>
                    <p class="card--footer">Total hidden articles</p>
                </div>
                <div class="card-bar bg--green"></div>
            </div>
            </a>
            {% comment %} END {% endcomment %}
        </div>
    {% comment %} end info cards {% endcomment %}

    {% comment %} |||||||||COMMON FOR MANY PAGES|||||||||| {% endcomment %}
        {% comment %} VISIT WEBSITE {% endcomment %}
        <div class="bfr-r-a">
            <div id="bfr-r-a">
                    <i class="fas fa-chart-line "></i>
                <div class="d-inline" style="padding: 0 10px;">
                    <!--T/B, L/R  -->
                    <h5 style="margin: 0;">Recent Published Articles</h5>
                    <span>List of your recently published articles.</span>
                </div>
            </div>
            <div class="visit-website">
                <button><a href="{% url 'blog:blog_home' %}">
                        <i class="fa fa-paper-plane" style="padding-right: 10px;color: #0a600a;"></i>
                        Visit website
                    </a></button>
            </div>
        </div>
        {% comment %} END OF VISIT WEBSITE  {% endcomment %}

        {% comment %} RECENT ARTICLES {% endcomment %}
        <div class="recent-articles">
            <div id="r-a-heading">
                <h2> Recent Published Articles

            </div>
            {% for blog in recent_blogs %}
            <div id="r-a-body">
                <div class="r-a-body">
                    <div class="img" >
                        <img class="" src="{{ blog.image.url }}" alt="" height="80" width="130">
                    </div>
                    <div style="padding-left: 10px;">
                        <div>
                            <ol class="post-arthur">
                                <li><h6>Title:</h6> <span>{{blog.title}}</span> </li>
                                <li><h6>Arthur<i>:</i></h6> <span>{{ blog.author.username }}</span> </li>
                            </ol>

                        </div>
                        <div class="meta mb-1">
                            <span class="date">
                            <b>Published:</b> 
                            <i>{% comment %} {{ blog.date_published|timesince|slice:":9"}} ago {% endcomment %}
                                {{ blog.date_published|timesince|slice:":20"|add:" ago" }}
                            </i>
                            </span>
                            <span class="date">
                                <b>Status:</b> 
                                <i>
                                    {{ blog.status }}
                                </i>
                            </span>
                            {% comment %} if rected is True {% endcomment %}
                            {% if blog.rejected %} 
                                <span class="text-warning date">Rejected <i class="bi bi-x-octagon"></i></span>
                                {% comment %} if approved is True {% endcomment %}
                            {% elif blog.approved %}
                                <span class="text-success date">Approved <i class="bi bi-check2-square"></i></span>
                                {% comment %} if none of the above is true {% endcomment %}
                            {% else %}
                                <span class="text-info date">Not verified <i class="bi bi-app-indicator"></i></span>
                                {% comment %} end {% endcomment %}
                            {% endif %}
                            <span class="time">{{ blog.word_count }} words</span>
                            <span class="time">{{ blog.read_time }} read</span>
                            <span class="comment">{{ blog.formatted_views_count }} views</span>
                            <span class="comment"><a href="#">{{ blog.comment_count }} comments</a></span>
                            {% comment %} dropdown {% endcomment %}
                            <div class="dropdown time">
                                <button class="btn dropdown-toggle" type="button" id="time-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-chevron-down dropdown-btn"></i>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="time-dropdown">
                                    <li>
                                        <a class="dropdown-item confirm-btn" 
                                        data-title="Are you sure you want to edit {{blog.title}}?"
                                        data-id = "edit"
                                        {% comment %} data-message="Once you edit it, original content will be lost."  {% endcomment %}
                                        data-url="{% url 'blog:blog_edit' slug=blog.slug %}" 
                                        data-button="Edit"
                                        data-bs-toggle="modal">
                                        Edit Article
                                        </a>
                                    </li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <a class="dropdown-item confirm-btn" 
                                    data-title="Are you sure you want to Hide {{blog.title}}?"
                                    data-id="hide"
                                    {% comment %} data-message="Once you hide it will not be available for other."  {% endcomment %}
                                    data-url="{% url 'blog:blog_hide' slug=blog.slug %}" 
                                    data-button="Hide"
                                    data-bs-toggle="modal">
                                    Hide Article
                                    </a>
                                </li>
                                </ul>
                            </div>
                            {% comment %}end of dropdown {% endcomment %}
                        </div>
                        <a class="r-a-more-link" href="{% url 'blog:das_article_detail' slug=blog.slug %}">View details →</a>
                        <hr class="solid" style="height: 6px;margin: 0.5rem 0;"> <!-- Solid divider -->
                    </div>
                </div>
            </div>
            {% empty %}
            <div>No blogs published yet.</div>
            {% endfor %}
        </div>
        {% comment %} END OF RECENT ARTICLES {% endcomment %}
    {% comment %} |||||||||END COMMON FOR MANY PAGES|||||||||| {% endcomment %}
</section>
{% comment %} <!-- end Home --> {% endcomment %}


{% endblock content %}

{%block js%}
{%endblock js%}