blog/urls.py
from django.urls import path, include
from .views.article_v import *
from .views.subncategories_v import *
from .views.dashboard.dashboard_home_v import *
from .views.dashboard.dashboard_article_v import *
from .views.dashboard.dashboard_many_v import *
from .views.dashboard.subncategory_d_v import *
from .views.tags_v import tag_blogs
from .views.dynamic_search_JS_V import *


app_name = 'blog'

urlpatterns = [
    path('articles-available/', blog_home, name='blog_home'),
    path('article view/<slug:slug>/', blog_detail, name='blog_detail'),
    path('category article list/<slug:slug>/', category_detail, name='category_detail'),
    path('subcategory article list/<slug:slug>/', subcategory_detail, name='subcategory_detail'),
    path('artcles/tagged/<slug:tag_slug>/', tag_blogs, name='tag_blogs'),
    
    #Dashboard Views
    # path('<slug:slug>/', article_detail, name='article_detail')
    path('dashboard/', dashboard_home, name='dashboard_home'),
    path('create/', blog_create, name='blog_create'),
    
    #DASHBOARD >>>>>>> : dashboard_article_v.py
    path('articles/<slug:slug>/', das_article_detail, name='das_article_detail'),
    path('edit/<slug:slug>/', blog_edit, name='blog_edit'),
    path('approve/<slug:slug>/', blog_approve, name='blog_approve'),
    path('reject/<slug:slug>/', blog_reject, name='blog_reject'),
    path('hide/<slug:slug>/', blog_hide, name='blog_hide'),
    path('unhide/<slug:slug>/', blog_unhide, name='blog_unhide'),
    path('delete/<slug:slug>/', blog_delete, name='blog_delete'),
    # used when using the id to get the data
    path('get_category_by_subcategory/<int:subcategory_id>/', 
         get_category_by_subcategory, name='get_category_by_subcategory'),
    # -----------------------------------------------------------//
        #   used when using slug to get the data
    # path('get_category_by_subcategory/<slug:subcategory_slug>/', 
    #      get_category_by_subcategory, name='get_category_by_subcategory'),
       #-----------------------------------------------------------------------//
    #-----------END DASHBOARD >>>>>>> : dashboard_article_v.py ------------//
    
    path('category/create/', category_create, name='category_create'),
    path('category/edit/<int:id>/', category_edit, name='category_edit'), #will be usin the id instead of slug
    path('category-list/', category_list, name='category_list'),
    
    path('subcategory/create/', subcategory_create, name='subcategory_create'),
    path('subcategory/edit/<int:id>/', subcategory_edit, name='subcategory_edit'),
    path('subcategory list/', subcategory_list, name='subcategory_list'),
    # dashboard_many_v.py
    path('recent articles/', recent_article_list, name='recent_article_list'),
    path('drafted articles/', drafted_article_list, name='drafted_article_list'),
    path('published articles/', published_article_list, name='published_article_list'),
    path('deleted articles/', hidden_article_list, name='hidden_article_list'),
    path('written articles/', written_article_list, name='written_article_list'),
    path('approved articles/', approved_article_list, name='approved_article_list'),
    path('rejected articles/', rejected_article_list, name='rejected_article_list'),
    
    # Add this URL pattern for search suggestions
    path('open-dropeddown-article/<slug:articleSlug>/', open_dropdown_article, name='open_dropdown_article'),
    path('blog-search-results/', blog_search_results, name='blog_search_results'),
    path('blog_search/ajax_search/', blog_ajax_search, name='blog_ajax_search'),
    
]

car_garage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# Admin Customization
admin.site.site_header = "Login to CDT"
admin.site.site_title = "Welcome to CDT Dashboard"
admin.site.index_title = "Welcome to this Portal"

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('contact_us/', include('contact_us.urls')),
    path('', include('visitors_counter.urls')),
]
# if settings.DEBUG:# Only add this when we in debug mode
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# else:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from .views import *
from .admin_views.service_category_edit_V import *
from .admin_views.serviceoffered_edit_view import *
from .admin_views.service_list_view_V import *

# app_name = 'services'
urlpatterns = [
    path('', services, name='services'),
    path('serives-under/<slug:slug>/', services_offered, name='services_offered'),
    path('serivces-category-list/', view_service_categories, name='view_service_categories'),
    path('category/<int:category_id>/', services_of_category, name='services_of_category'),

    path('create-services-page/', create_services_category, name='create_services_category'),
    path('create-services-page/<int:pk>/', create_services_category, name='create_services_category'),
    path('category-delete/<int:pk>/', category_delete, name='category_delete'),
    
    path('edit-service/<int:pk>/', edit_service_offered, name='edit_service_offered'),
    path('delete-service-offered/<int:pk>/', delete_service_offered, name='delete_service_offered'),   
]

services/models.py
from django.db import models
from PIL import Image
from django.utils.text import slugify
from phonenumber_field.modelfields import PhoneNumberField

class Appointment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = PhoneNumberField()
    date = models.DateField()
    time = models.TimeField()
    service = models.ForeignKey('ServiceOffered', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

class ServiceCategory(models.Model):
    category_name = models.CharField(default='Engine services', max_length=200, null=False)
    cat_description = models.TextField(
        default='CaT- Lorem ipsum dolor sit amet, consectetur adipisicingpra esentium eveniet eum libero assumenda.',
        null=False
    )
    img_icon = models.ImageField(default='service_default.png', upload_to='services_Icons',null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)  # Add a slug field

    def __str__(self):
        return self.category_name

    def save(self, *args, **kwargs):
        # Automatically generate the slug based on the category_name
        if not self.slug:
            self.slug = slugify(self.category_name)
        super(ServiceCategory, self).save(*args, **kwargs)
        
        img = Image.open(self.img_icon.path)
        if img.height > 100 or img.width > 110:
            output_size = (110, 100)
            img.thumbnail(output_size)
            img.save(self.img_icon.path)
class ServiceOffered(models.Model):
    category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)
    service_name = models.CharField(default='Dental Services', max_length=100, null=False)
    description = models.TextField(
        default='Lorem ipsum dolor sit amet, consectetur adipisicingpra esentium eveniet eum libero assumenda.',
        null=False
    )
    def __str__(self):
        return self.service_name

    def save(self, *args, **kwargs):
        super(ServiceOffered, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Perform any necessary cleanup before deleting (if applicable)
        super(ServiceOffered, self).delete(*args, **kwargs)

services/forms.py
# forms.py
from django import forms
from .models import *
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

class AppointmentForm1(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['name', 'email',]
class AppointmentForm2(forms.ModelForm):
    phone = PhoneNumberField(
            widget=PhoneNumberPrefixWidget(initial='KE', attrs={'class': 'p-no'})
        )
    class Meta:
        model = Appointment
        fields = ['phone',]
class AppointmentForm3(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['date', 'time',] 
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }
class AppointmentForm4(forms.ModelForm):
    service = forms.ModelChoiceField(
        queryset=ServiceOffered.objects.all(),  # Replace YourServiceModel with the actual model you're using
        empty_label="Click to choose a service",  # Set the default placeholder text
    )
    class Meta:
        model = Appointment
        fields = ['service', 'message']
    

class ServiceCategoryForm(forms.ModelForm):
    class Meta:
        model = ServiceCategory
        fields = ['category_name','img_icon', 'cat_description', ]  

class ServiceOfferedForm(forms.ModelForm):
    class Meta:
        model = ServiceOffered
        fields = ['service_name', 'description',]
        
ServiceOfferedFormSet = forms.inlineformset_factory(
    ServiceCategory,ServiceOffered,
    form=ServiceOfferedForm,
    extra=0,  # Number of empty forms to display
)

services/views.py
from django.shortcuts import render,get_object_or_404

from django.http import HttpResponse
from django.contrib import messages
from main.models.models import *
from django.contrib.auth.models import User
from twilio.rest import Client
# from .forms import ContactForm
from django.shortcuts import render, redirect
from .forms import *
from .models import *
# Create your views here.
def services(request):
    service_categories = ServiceCategory.objects.all()
    messages =''
    if request.method == 'POST':
        form1 = AppointmentForm1(request.POST)
        form2 = AppointmentForm2(request.POST)
        form3 = AppointmentForm3(request.POST)
        form4 = AppointmentForm4(request.POST)
        print('time and date')
        print(form1)
        if form1.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid():
            # Create an instance of the Appointment model and populate it with data
            appointment = Appointment(
                name=form1.cleaned_data['name'],
                email=form1.cleaned_data['email'],
                phone=form2.cleaned_data['phone'],
                date=form3.cleaned_data['date'],
                time=form3.cleaned_data['time'],
                service=form4.cleaned_data['service'],
                message=form4.cleaned_data['message']
            )
            appointment.save()
            print(appointment)
            
            messages = "Appointment was succefully booked, we will get back to you in due time"
            # Get the previous URL
            previous_url = request.META.get('HTTP_REFERER')
            # return to the previous Url if available
            return redirect(previous_url)
    
    else:
        form1 = AppointmentForm1()
        form2 = AppointmentForm2()
        form3 = AppointmentForm3()
        form4 = AppointmentForm4()
    context = {
        'service_categories': service_categories,
        'form1': form1,
        'form2': form2,
        'form3': form3,
        'form4': form4,
        'messages': messages, 
        
        }

    # Render the response and send it back!
    return render(request, 'home_page_includes/services.html', context)

def services_offered(request, slug):
    category = get_object_or_404(ServiceCategory, slug=slug)
    services = category.serviceoffered_set.all()
    form1 = AppointmentForm1()
    form2 = AppointmentForm2()
    form3 = AppointmentForm3()
    form4 = AppointmentForm4()

    if request.method == 'POST':
        form1 = AppointmentForm1(request.POST)
        form2 = AppointmentForm2(request.POST)
        form3 = AppointmentForm3(request.POST)
        form4 = AppointmentForm4(request.POST)
        if form1.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid():
            try:
                form1.save()
                form2.save()
                form3.save()
                form4.save()
                success_message = "Appointment booked successfully."
            except Exception as e:
                # Handle exceptions (e.g., database errors)
                error_message = f"An error occurred: {str(e)}"
    
    context = {
        'form1': form1,
        'form2': form2,
        'form3': form3,
        'form4': form4,
        'services': services,
        }

    # Render the response and send it back!
    return render(request, 'services/services_offered.html', context)




# def send_whatsapp_message(appointment):
#     account_sid = 'YOUR_TWILIO_ACCOUNT_SID'
#     auth_token = 'YOUR_TWILIO_AUTH_TOKEN'
#     twilio_number = 'YOUR_TWILIO_PHONE_NUMBER'
#     recipient_number = 'RECIPIENT_PHONE_NUMBER_WITH_COUNTRY_CODE'

#     client = Client(account_sid, auth_token)
#     message = f"New Appointment:\nName: {appointment.name}\nEmail: {appointment.email}\nPhone: {appointment.phone}\nDepartment: {appointment.department}\nDay: {appointment.day}\nTime: {appointment.time}\nMessage: {appointment.message}"

#     client.messages.create(
#         body=message,
#         from_=twilio_number,
#         to=recipient_number,
#         provide_feedback=True
#     )

templates/services/appointments.html
{% block head %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>

<style>
    p{
        margin-bottom: 5px !important;
    }
    select{
        border: 1px solid #c9e6ff;
      }
      .phone-no{
        display: flex;
        padding-top: 0 !important;
      }
      .phone-no select{
        width: 70px;
        margin-right: 5px;
      }
      select.P-no{
        width: fit-content;
      }
      .date-time{
        display: flex;
        justify-content: space-between;
      }
      .date-time p{
        max-width: 115px;
      }
      .text-area p{
        display: flex;
        flex-direction: column;
      }
      textarea{
        height: 70px;
      }
</style>
{% endblock head %}
<div class="div2">
    <div>
        <h5 >+Book Appointment</h5>
    </div>
    <div class="form">
        <form method="post">
            {% csrf_token %}
            {{ form1.as_p }}
            <div id="phone-no" style="padding-top: 10px;">
                
                <label for="id_phone_number">Phone number:</label>
                
                <p class="phone-no">
                 {{form2.phone}}
                </p>
                <script>
                  document.addEventListener("DOMContentLoaded", function () {
                      // Get the select element
                      var select = document.getElementById("id_phone_0");
          
                      // Initialize a variable to store the previous selected option text
                      var previousOptionText = "";
          
                      // Initialize a variable to store the index of the option currently displaying in the
                      // select. before selecting a new option
                      var currentIndex = -1;
                      // Function to update the previousOptionText and currentIndex variables
                      function updateSelection() {
                          var selectedOption = select.options[select.selectedIndex];
                          var fullText = selectedOption.textContent;
                          // Use a regular expression to extract the country code (last part)
                          var countryCodeMatch = fullText.match(/\+\d+$/);
                          if (countryCodeMatch) {
                              var countryCode = countryCodeMatch[0];
                              // Update the text of the selected option to display only the country code
                              selectedOption.text = countryCode;
                              //console.log(selectedOption)
                              previousOptionText = fullText;
                              currentIndex = select.selectedIndex;
                          }
                      }
          
                      // Initial update
                      updateSelection();
          
                      // Add an event listener for the "change" event on the select element
                      select.addEventListener("change", function () {
                          // Get the selected option text
                          var selectedOptionText = select.options[select.selectedIndex].text;
          
                          // Do something with the selected option text, e.g., save it to a variable
                          //console.log("Selected Option Text:", selectedOptionText);
          
                          // Do something with the previous option text if needed
                          //console.log("Previous Option Text:", previousOptionText);
          
                          // Do something with the current index if needed
                          //console.log("Current Index:", currentIndex);
          
                          // You can also replace the text of the current select option with the saved text
                          select.options[currentIndex].text = previousOptionText;
          
                          // Update the previousOptionText and currentIndex variables
                          updateSelection();
                      });
                  });
                </script>
            </div>
            <div class="date-time">
                {{ form3.as_p }}
            </div>
            {% comment %} <input type="text" id="id_date" name="date">
            <input type="text" id="id_time" name="time"> {% endcomment %}
            <div class="text-area" style="padding-top: 10px;">
            {{ form4.as_p }}
            </div>
            <div class="form-group button">
                <button type="submit">Submit</button>
            </div>
            <p class="text-center" style="margin-bottom: 0 !important;">or</p>
            <div class="form-group button" style="margin-top: 5px;">
              <a href="" id='whatsapp-url' target="_blank" style="font-weight: 700;">Contact on Whatsapp</a>
            </div>
        </form>
    </div>
</div>

templates/services/services.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title> 
  Services
</title>
{{ form.media }}
<link rel="stylesheet" href="{% static 'css/services.css' %}" type="text/css">
<style>
    .services{
      /*background-image: url('{{ background_image_url }}'); For dynamic BG image*/ 
      background-image: url("{% static 'images/water_blue_4_BG.jpg' %}");
      background-size: cover; /* Scale the background image to cover the entire container */
      background-position: center; /* Center the background image within the container */
      min-height: 200px;
      /*padding-bottom: 100px;*/
      position: relative;
    }
    /*fOR ENFORCING BLUR ON THE IMAGE*/
    .services::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        width: 100%;
        height: inherit;
        background: inherit;
        filter: blur(90px);
    }
    .div1, .div2{
        /* to help with blur of background image */
        position: inherit;
    }
    .service-- a{
        text-decoration:none;
    }
  </style>
{% endblock head %}

{% block content %}
<section class="services"> <!-- s2 -->
    <div class="div1">
        {% for category in service_categories %}
        <div class="service--">
            <a href="{% url 'services_offered' slug=category.slug %}">
                <div class="service edit-icon-h">
                    <div>{{ category.iconInput|safe }}</div>
                    <h6 style="font-weight: 700;">
                        {{ category.category_name }}
                    </h6>
                    <p>
                        {{ category.cat_description }} 
                    </p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    {% include 'services/appointments.html' %}  
</section>
{% endblock content %}

templates/services/services_offered.html
{% extends 'base.html' %}
{% load static %}



{% block head %}
<title> 
  Services
</title>
<link rel="stylesheet" href="{% static 'css/services.css' %}" type="text/css">
<style>
    .services{
      /*background-image: url('{{ background_image_url }}'); For dynamic BG image*/ 
      background-image: url("{% static 'images/water_blue_4_BG.jpg' %}");
      background-size: cover; /* Scale the background image to cover the entire container */
      background-position: center; /* Center the background image within the container */
      min-height: 200px;
      /*padding-bottom: 100px;*/
      position: relative;
    }
    /*fOR ENFORCING BLUR ON THE IMAGE*/
    .services::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        width: 100%;
        height: inherit;
        background: inherit;
        filter: blur(90px);
    }
    .div1, .div2{
        /* to help with blur of background image */
        position: inherit;
    }
  </style>
{% endblock head %}

{% block content %}
<section class="services"> <!-- s2 -->
    <div class="div1">
        {% for service in services %}
            <div class="service">
                <div><i class="fa-icon fa-solid fa-truck-medical"></i></div>
                <h6 style="font-weight: 700;">
                    {{ service.service_name }}
                </h6>
                <p>
                    {{ service.description }}
                </p>
            </div>
        {% endfor %}
    </div>
    {% include 'services/appointments.html' %}
</section>
{% endblock content %}